# Generated by Django 4.2.7 on 2026-01-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20)),
                ('can_create_board', models.BooleanField(default=False)),
                ('can_create_automation', models.BooleanField(default=False)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('can_manage_billing', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role',)},
            },
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_name', models.CharField(default='free', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('next_payment_due', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core.organization')),
            ],
        ),
    ]
