# Generated by Django 4.2.7 on 2026-01-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pricingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='plan_name',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pricingplan'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_automations',
            field=models.IntegerField(default=100, help_text='Max automation runs per month'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_boards',
            field=models.IntegerField(default=10, help_text='Max boards allowed (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_users',
            field=models.IntegerField(default=5, help_text='Max users allowed (0 for unlimited)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for URL/API', null=True, unique=True),
        ),
    ]
