# Generated by Django 4.2.7 on 2026-01-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
