# Generated by Django 4.2.7 on 2026-01-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['order', 'price']},
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='features',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='button_text',
            field=models.CharField(default='Get Started', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, help_text='Short tagline for the plan'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.pricingplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
