# Generated by Django 4.2.7 on 2026-01-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pricingplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='URL or path (e.g., /pricing/ or https://google.com)', max_length=200)),
                ('section', models.CharField(choices=[('products', 'Products'), ('solutions', 'Solutions'), ('resources', 'Resources'), ('company', 'Company')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
