# Generated by Django 4.2.7 on 2026-01-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(help_text='HTML Content for the page body')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('features', models.JSONField(default=list, help_text='List of features')),
                ('is_active', models.BooleanField(default=True)),
                ('recommended', models.BooleanField(default=False)),
                ('user_limit', models.IntegerField(default=1)),
                ('board_limit', models.IntegerField(default=3)),
                ('automation_limit', models.IntegerField(default=100)),
            ],
        ),
    ]
