# Generated by Django 4.2.7 on 2026-01-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
