# Generated by Django 4.2.7 on 2026-01-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_delete_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price', max_digits=6)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_period', models.CharField(default='month', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Short tagline for the plan')),
                ('is_popular', models.BooleanField(default=False, help_text='Highlight this plan?')),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True, help_text='Check if included, uncheck if excluded/crossed out')),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='marketing.pricingplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
