# Generated by Django 4.2.7 on 2026-01-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_pricingplan_planfeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanFeature',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
