# Generated by Django 4.2.7 on 2026-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_delete_planfeature_delete_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('projectflow_text', models.CharField(help_text="Text for our column (e.g., '✅ Included')", max_length=100)),
                ('monday_text', models.CharField(help_text="Text for Monday.com column (e.g., '❌ Complex')", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
