# Generated by Django 4.2.7 on 2026-01-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='webapp.board'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationrule'),
        ),
    ]
