# Generated by Django 4.2.7 on 2026-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Send Email')", max_length=100)),
                ('code', models.SlugField(help_text="Code identifier (e.g., 'send_email')", unique=True)),
                ('icon', models.CharField(default='mail', help_text='Icon identifier', max_length=50)),
                ('description', models.TextField(help_text='User-facing description')),
                ('color', models.CharField(default='orange', help_text='Color theme (orange, pink, purple, etc.)', max_length=20)),
                ('requires_value', models.BooleanField(default=False, help_text='Does this action need a value selection?')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TriggerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Status Changed')", max_length=100)),
                ('code', models.SlugField(help_text="Code identifier (e.g., 'status_change')", unique=True)),
                ('icon', models.CharField(default='lightning', help_text='Icon identifier', max_length=50)),
                ('description', models.TextField(help_text='User-facing description')),
                ('color', models.CharField(default='blue', help_text='Color theme (blue, green, purple, etc.)', max_length=20)),
                ('requires_value', models.BooleanField(default=False, help_text='Does this trigger need a value selection?')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
