# Generated by Django 4.2.7 on 2026-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public')], default='team', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('calendar', 'Calendar')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('status', 'Status'), ('date', 'Date'), ('person', 'People'), ('number', 'Numbers'), ('dropdown', 'Dropdown'), ('priority', 'Priority'), ('checkbox', 'Checkbox'), ('file', 'File'), ('formula', 'Formula')], max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
