# Generated by Django 4.2.7 on 2026-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_board_privacy_board_type_alter_column_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
