# Generated by Django 4.2.7 on 2026-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_itemupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('calendar', 'Calendar'), ('gantt', 'Gantt Chart')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('status', 'Status'), ('date', 'Date'), ('person', 'People'), ('number', 'Numbers'), ('dropdown', 'Dropdown'), ('priority', 'Priority'), ('checkbox', 'Checkbox'), ('file', 'File'), ('formula', 'Formula'), ('timeline', 'Timeline'), ('tags', 'Tags')], max_length=20),
        ),
    ]
