# Generated by Django 4.2.7 on 2026-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_item_parent_itemattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('status', 'Status'), ('date', 'Date'), ('person', 'People'), ('number', 'Numbers'), ('dropdown', 'Dropdown'), ('priority', 'Priority'), ('checkbox', 'Checkbox'), ('file', 'File'), ('formula', 'Formula'), ('timeline', 'Timeline'), ('tags', 'Tags'), ('link', 'Link'), ('world_clock', 'World Clock'), ('item_id', 'Item ID'), ('phone', 'Phone'), ('location', 'Location'), ('rating', 'Rating'), ('progress', 'Progress'), ('email', 'Email'), ('vote', 'Vote')], max_length=20),
        ),
    ]
