# Generated by Django 4.2.7 on 2026-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_column_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('status', 'Status'), ('date', 'Date'), ('person', 'People'), ('number', 'Numbers'), ('dropdown', 'Dropdown'), ('priority', 'Priority'), ('checkbox', 'Checkbox'), ('file', 'File'), ('formula', 'Formula'), ('timeline', 'Timeline'), ('tags', 'Tags'), ('link', 'Link'), ('world_clock', 'World Clock'), ('item_id', 'Item ID'), ('phone', 'Phone'), ('location', 'Location'), ('rating', 'Rating'), ('progress', 'Progress'), ('email', 'Email'), ('vote', 'Vote'), ('creation_log', 'Creation Log'), ('last_updated', 'Last Updated'), ('auto_number', 'Auto Number'), ('country', 'Country'), ('color_picker', 'Color Picker'), ('time_tracking', 'Time Tracking'), ('week', 'Week'), ('hour', 'Hour')], max_length=20),
        ),
    ]
